POPLAR_ENGINE_OPTIONS: {}
batch_size: 90
batchnorm_momentum: 0.1
config: 'resnet50-mk2'
data: 'real'
dataloader_rebatch_size: None
dataloader_worker: 32
device_iterations: 1
efficientnet_expand_ratio: 6
efficientnet_group_dim: 1 
eight_bit_io: True
enable_fast_groupnorm: False
exchange_memory_target: 'cycles'
half_partial: True
input_image_padding: False
iterations: 100
model: 'resnet50'
model_cache_path: None
norm_eps: 1e-05
norm_num_groups: 32
norm_type: 'batch'
normalization_location: 'ipu'
num_io_tiles: 0
pipeline_splits: []
precision: '16.16'
profile: False
random_weights: False
replicas: 1
use_popdist: False
webdataset_memory_cache_ratio: 0.0